# Generated by Django 4.1.3 on 2022-11-08 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='task',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='done',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklist',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
